###################################################################
"""
(
	Before running this script make sure that the only folders
	in the curr directory are the ones that are generated by the code
	i.e folders with names Y20XX-YY and no other folders
)
Parses the files in folders Y20XX-YY. Tsv files are created from
these .html files and are stored in the same folder as the .html file
"""
###################################################################




import re
import mechanize
from bs4 import BeautifulSoup
from os import listdir
import os.path
import os
import time


def htmlToTxtConverter(htmlText, outputFileName):
	"""
	Takes htmltext string and finds the tabulated data in it. For each row
	entry in table, it separtes them with tab. Finally combines each row
	in a single string and writes it down to the file outputFileName and exits
	"""
	fd = open(outputFileName, 'w')
	soup = BeautifulSoup(htmlText, "lxml")
	table = soup.find("table") #get the first table in the entire html

	for row in table.find_all("tr"):   #.find_all("tr"):
		heading = []
		count = 0
		for cols in row.find_all("td"): 
			if(count >= 5): #  Limit only to 5 columns
				break
			tempcol = cols.get_text()
			if (tempcol.strip() == ""):
				tempcol = "."
			heading.append(' '.join(str(tempcol).strip().split()))
			count = count +1
		fd.write('\t'.join(map(str, heading)))
		fd.write('\n')
	fd.close()

def getFilesInDir(directory):
	"""
	Creates a list of files (not directories) in the "directory" folder.
	"directory" must be a string of the form "/home/deepak/......../FolderContainingY20XX-YY.htmlFiles"
	"""
	return [ f for f in listdir(directory) if os.path.isfile(os.path.join(directory,f)) ]


start_time = time.time()
old_time = time.time()

parentDirectoryListing = os.walk("./") #Get the list of all folders
yearDirectory = []
skipfirsttime = True  #Skip the first time bcoz element [0] is "./"
for dirlisting in parentDirectoryListing:
	if(skipfirsttime == True):
		skipfirsttime = False
	else:
		yearDirectory.append(str(dirlisting[0])) # 0 is for directories
#print yearDirectory

for yearDir in yearDirectory:
	filesInDir = getFilesInDir(str(yearDir))
	print filesInDir
	print yearDir
	#raw_input()
	for i in range(len(filesInDir)):
		if (str(filesInDir[i]).endswith(".html")):
			#newdirname = "./" + '.'.join(filesInDir[i].split(".")[:-1])
			newfilename = '.'.join(filesInDir[i].split(".")[:-1]) + ".tsv"
			extnewfilename = str(yearDir) + "/" + newfilename
			htmlfileread = open(str(yearDir)+"/"+filesInDir[i], 'r')
			htmlToTxtConverter(htmlfileread.read(), extnewfilename)
			htmlfileread.close()

TotalTimeTaken = time.time() - start_time
print("Total Time Taken: %s \n" %(TotalTimeTaken))